### ISSUE TITLE
D_fake loss and D_real loss do not converge

### ISSUE THREAD

**Issue by patricegaofei** [rlct1/gin#2]
Dear authors,
Thank you very much for sharing your codes, and congratulations on the great achievement. I have tried to run your codes on my own dataset. However, D_fake loss and D_real loss do not converge. Their values remain around 1. 922 and 2. 021. I have even increased the epoch number to 140, assigned different values to the style loss, tv loss, l1 loss and learning rate, etc. There was no improvement. Please, how can I fix this? Has anyone encountered the same problem?

Any suggestions or comments would be highly appreciated.

Kind regards,
Patrice

**Comment by rlct1** [comment]
Dear Patrice,

If I understand your question correctly. What you mean is that your D_fake loss and D_real loss remain at around 1.922 and 2.021 respectively. 

To the best of my knowledge, this should not be a problem as D_fake loss and D_real loss should get similar values theoretically. Note that D_fake loss and D_real loss are used to update the discriminator and discriminator is responsible for distinguishing fake images (completed images) from real images. If typical adversarial loss is used, the best situation is that both D_fake loss and D_real loss have the value of 0.5. This means that generator can complete images that are very similar to real images. In such a case, both D_fake loss and D_real loss will remain at 0.5. I have also tried the typical adversarial loss. But the training is not stable (i.e. D_fake loss and D_real loss are not stable). I have also tried Least Square GAN loss, it seems better. Finally, I chose to use Hinge loss as it becomes stable very early during training. 

I think the main point is that the values of D_fake loss and D_real loss depend on which GAN loss you are using (e.g. LSGAN loss, hinge loss, the most adversarial loss, etc.). It will be ok as long as both the values are stable and remain almost the same. I can tell you that my loss is similar to yours. For a more general dataset like ADE20K, my D_fake loss and D_real loss are around 1.9x. For a specific dataset, like CelebA-HQ, my D_fake loss and D_real loss are around 1.5x (a bit lower). 

You may have a try on other GAN losses (e.g. LSGAN, https://wiseodd.github.io/techblog/2017/03/02/least-squares-gan/). From my point of view, you may have a look on the generated images from your model. If the generated images get better and better, It should be ok. 


Best Regards,
Ron

**Comment by patricegaofei** [comment]
Hello dear Ron,
Thank you very much for your detailed explanation. I will try other GAN losses and see how things go.

**Comment by rlct1** [comment]
Dear Patrice,

You're welcome. Very happy to answer your question:)

**Comment by patricegaofei** [comment]
Hello Ron,

I have faced some challenges while trying to implement the LSGAN loss as suggested. Please, could we exchange through email? (patrice123china1@gmail.com)
