### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by kodaig** [rlct1/gin#3]
Dear authors,

I have tried your inpainting model on my data and the result was impressive.
Thank you for sharing the great work.

By the way, this repository is not licensed.
Would you tell me if you are going to add license in the future?

Best,
Kodai

**Comment by rlct1** [comment]
Dear Kodai, 

Thanks for your appreciation and asking. BSD license has been added. Thank you very much.



Best,
Ron

**Comment by kodaig** [comment]
Dear Ron,

Thank you very much! I appreciate that.
